#!/usr/bin/env python

import sys
import os

local_root=os.environ["local_root"]
local_svn_root=os.environ["local_svn_root"]


f = open(sys.argv[1], "r")
for line in f:
    local_path = local_root+"/"+line.strip()
    
    if not os.path.exists(local_path):
        local_path=line.strip()
        if not os.path.exists(local_path):
            raise Exception("can't find file in local_root:"+local_path)
    

    local_svn_path=local_svn_root+local_path[len(local_root):]
    if not os.path.exists(local_svn_path):
        raise Exception("can't find svn path in local_svn_root:" + local_svn_path)

    print "echo \"checking file:" + line.strip() + "\""
    print "echo \"enter to diff\""
    print "read"
    print "diff "+local_path+" "+local_svn_path
    print "echo \"enter to copy\""
    print "read"
    print "cp " + local_path+" "+local_svn_path

    




